export const AREA_QUESTIONS = [
  {
    areaId: 'transport',
    areaLabel: 'Transporte',
    areaEmoji: '🚗',
    areaColor: '#4a90d9',
    questions: [
      {
        id: 'car',
        text: '¿Cuántos km recorres en coche o furgoneta al año?',
        type: 'single',
        options: [
          { value: 'none',     label: 'No tengo coche' },
          { value: 'low',      label: 'Menos de 8.000 km' },
          { value: 'med',      label: '8.000 – 20.000 km' },
          { value: 'high',     label: 'Más de 20.000 km' },
          { value: 'electric', label: 'Coche eléctrico (uso habitual)' },
        ],
      },
      {
        id: 'moto',
        text: '¿Usas moto o ciclomotor habitualmente?',
        type: 'single',
        options: [
          { value: 'no',     label: 'No' },
          { value: 'little', label: 'Ocasionalmente' },
          { value: 'daily',  label: 'A diario o casi a diario' },
        ],
      },
      {
        id: 'publicTransport',
        text: '¿Cómo te desplazas habitualmente en tu ciudad?',
        type: 'single',
        options: [
          { value: 'walk_bike', label: 'A pie o en bicicleta' },
          { value: 'public',    label: 'Metro, bus o tren de cercanías' },
          { value: 'mixed',     label: 'Combinado (público + coche)' },
          { value: 'car_only',  label: 'Solo en coche privado' },
        ],
      },
      {
        id: 'flights',
        text: '¿Qué tipos de vuelos has hecho este año?',
        info: 'Selecciona todos los que apliquen. Si no vuelas, continúa sin marcar.',
        type: 'multi',
        options: [
          { value: 'national',  label: 'Vuelos nacionales o de corta distancia (≤2h)' },
          { value: 'european',  label: 'Vuelos europeos (2–5h)' },
          { value: 'long_haul', label: 'Vuelos intercontinentales o de larga distancia (>5h)' },
        ],
      },
    ],
  },
  {
    areaId: 'energy',
    areaLabel: 'Hogar',
    areaEmoji: '🏠',
    areaColor: '#e8a020',
    questions: [
      {
        id: 'householdSize',
        text: '¿Cuántas personas vivís en tu hogar?',
        type: 'single',
        options: [
          { value: '1',  label: '1 persona' },
          { value: '2',  label: '2 personas' },
          { value: '3',  label: '3 personas' },
          { value: '4+', label: '4 o más personas' },
        ],
      },
      {
        id: 'homeType',
        text: '¿En qué tipo de vivienda vives?',
        type: 'single',
        options: [
          { value: 'flat_small', label: 'Piso pequeño o compacto (<70 m²)' },
          { value: 'flat_large', label: 'Piso o apartamento grande (≥70 m²)' },
          { value: 'house',      label: 'Casa unifamiliar o adosado' },
        ],
      },
      {
        id: 'heating',
        text: '¿Cómo calientas tu hogar en invierno?',
        type: 'single',
        options: [
          { value: 'none',      label: 'No tengo calefacción' },
          { value: 'gas',       label: 'Gas natural o propano' },
          { value: 'oil',       label: 'Gasoil o gasóleo' },
          { value: 'electric',  label: 'Eléctrica (radiadores o suelo radiante)' },
          { value: 'heatpump',  label: 'Bomba de calor o aerotermia' },
        ],
      },
      {
        id: 'hasAC',
        text: '¿Usas aire acondicionado en verano?',
        type: 'single',
        options: [
          { value: 'no',     label: 'No o casi nunca' },
          { value: 'little', label: 'Puntualmente (pocas semanas)' },
          { value: 'yes',    label: 'Regularmente durante el verano' },
        ],
      },
      {
        id: 'renewable',
        text: '¿Tu hogar usa energía renovable?',
        type: 'single',
        options: [
          { value: 'yes',     label: 'Sí, placas solares o tarifa 100% verde' },
          { value: 'partial', label: 'Parcialmente (tarifa verde o comunidad solar)' },
          { value: 'no',      label: 'No, red eléctrica convencional' },
        ],
      },
      {
        id: 'homeHabits',
        text: '¿Cuáles de estos hábitos practicas en casa?',
        info: 'Selecciona todos los que apliquen.',
        type: 'multi',
        options: [
          { value: 'led',           label: 'Iluminación LED en toda la casa' },
          { value: 'short_shower',  label: 'Duchas cortas (menos de 5 min)' },
          { value: 'cold_wash',     label: 'Lavadora a baja temperatura (30–40°C)' },
          { value: 'thermostat',    label: 'Termostato regulado (19–21°C en invierno)' },
        ],
      },
    ],
  },
  {
    areaId: 'food',
    areaLabel: 'Alimentación',
    areaEmoji: '🥗',
    areaColor: '#5aab5a',
    questions: [
      {
        id: 'diet',
        text: '¿Cómo describirías mejor tu dieta habitual?',
        type: 'single',
        options: [
          { value: 'vegan',  label: 'Vegana (sin ningún producto animal)' },
          { value: 'veggie', label: 'Vegetariana (incluye huevos y lácteos)' },
          { value: 'flexi',  label: 'Flexitariana (poca carne, sobre todo aves o pescado)' },
          { value: 'omni',   label: 'Omnívora (como de todo con moderación)' },
          { value: 'meat',   label: 'Rica en carne roja (vacuno, cerdo, cordero)' },
        ],
      },
      {
        id: 'localFood',
        text: '¿Con qué frecuencia consumes productos locales o de temporada?',
        type: 'single',
        options: [
          { value: 'always',    label: 'Siempre o casi siempre' },
          { value: 'sometimes', label: 'A menudo' },
          { value: 'never',     label: 'Raramente o nunca' },
        ],
      },
      {
        id: 'foodWaste',
        text: '¿Cuánta comida acabas tirando cada semana?',
        type: 'single',
        options: [
          { value: 'none',   label: 'Casi ninguna, aprovecho todo' },
          { value: 'little', label: 'Poca (restos sueltos)' },
          { value: 'some',   label: 'Bastante (platos o paquetes enteros)' },
          { value: 'lot',    label: 'Mucha, desperdicio frecuentemente' },
        ],
      },
      {
        id: 'bottledWater',
        text: '¿Bebes agua del grifo o embotellada?',
        type: 'single',
        options: [
          { value: 'no',        label: 'Solo agua del grifo o filtrada' },
          { value: 'sometimes', label: 'Principalmente grifo, a veces embotellada' },
          { value: 'always',    label: 'Principalmente embotellada' },
        ],
      },
      {
        id: 'foodHabits',
        text: '¿Cuáles de estos hábitos tienes con la alimentación?',
        info: 'Selecciona todos los que apliquen.',
        type: 'multi',
        options: [
          { value: 'organic',    label: 'Compro productos ecológicos habitualmente' },
          { value: 'no_plastic', label: 'Evito envases de plástico o compro a granel' },
          { value: 'compost',    label: 'Hago compost o uso cubo de orgánico' },
          { value: 'meal_plan',  label: 'Planifico mis menús para no desperdiciar' },
        ],
      },
    ],
  },
  {
    areaId: 'consumption',
    areaLabel: 'Consumo',
    areaEmoji: '🛍️',
    areaColor: '#b07a30',
    questions: [
      {
        id: 'clothes',
        text: '¿Cuánta ropa nueva compras al año?',
        type: 'single',
        options: [
          { value: 'none', label: 'Casi nada o solo de segunda mano' },
          { value: 'few',  label: 'Menos de 10 prendas nuevas' },
          { value: 'many', label: '10 a 20 prendas nuevas' },
          { value: 'lots', label: 'Más de 20 prendas nuevas' },
        ],
      },
      {
        id: 'electronics',
        text: '¿Qué dispositivos electrónicos has comprado nuevos este año?',
        info: 'Selecciona todos los que hayas comprado.',
        type: 'multi',
        options: [
          { value: 'phone',    label: 'Smartphone o tablet' },
          { value: 'laptop',   label: 'Portátil, PC de sobremesa o consola' },
          { value: 'tv',       label: 'Televisor o monitor grande' },
          { value: 'wearable', label: 'Smartwatch, auriculares u otros pequeños' },
        ],
      },
      {
        id: 'appliances',
        text: '¿Qué electrodomésticos has comprado nuevos este año?',
        info: 'Selecciona todos los que hayas comprado.',
        type: 'multi',
        options: [
          { value: 'fridge',  label: 'Nevera, congelador o combi' },
          { value: 'washer',  label: 'Lavadora o lavavajillas' },
          { value: 'oven',    label: 'Horno, microondas o cocina' },
          { value: 'small',   label: 'Varios electrodomésticos pequeños' },
        ],
      },
      {
        id: 'hygiene',
        text: '¿Cómo calificarías tu consumo de productos de higiene y limpieza?',
        type: 'single',
        options: [
          { value: 'low',  label: 'Bajo: productos concentrados o a granel' },
          { value: 'med',  label: 'Medio: consumo habitual convencional' },
          { value: 'high', label: 'Alto: muchos productos y envases frecuentes' },
        ],
      },
      {
        id: 'smoking',
        text: '¿Fumas?',
        type: 'single',
        options: [
          { value: 'no',     label: 'No fumo' },
          { value: 'little', label: 'Ocasionalmente' },
          { value: 'yes',    label: 'Sí, a diario' },
        ],
      },
      {
        id: 'pets',
        text: '¿Qué mascotas tienes?',
        info: 'Selecciona todas las que tengas.',
        type: 'multi',
        options: [
          { value: 'dog_large', label: 'Perro grande (>15 kg)' },
          { value: 'dog_small', label: 'Perro pequeño (<15 kg)' },
          { value: 'cat',       label: 'Gato' },
          { value: 'other',     label: 'Otras mascotas (aves, conejos, etc.)' },
        ],
      },
    ],
  },
  {
    areaId: 'waste',
    areaLabel: 'Huella Digital',
    areaEmoji: '📱',
    areaColor: '#7a7aaa',
    questions: [
      {
        id: 'videoCalls',
        text: '¿Cuántas horas de videollamadas haces a la semana (Zoom, Teams, Meet...)?',
        type: 'single',
        options: [
          { value: 'none', label: 'Ninguna o casi ninguna' },
          { value: 'few',  label: 'Menos de 2 horas' },
          { value: 'some', label: '2 a 5 horas' },
          { value: 'lots', label: 'Más de 5 horas' },
        ],
      },
      {
        id: 'streaming',
        text: '¿Cuántas horas al día consumes contenido en streaming (Netflix, YouTube, Spotify...)?',
        type: 'single',
        options: [
          { value: 'none', label: 'Casi nada' },
          { value: 'low',  label: 'Menos de 1 hora' },
          { value: 'med',  label: '1 a 3 horas' },
          { value: 'high', label: 'Más de 3 horas' },
        ],
      },
      {
        id: 'socialMedia',
        text: '¿Cuántas horas al día pasas en redes sociales?',
        type: 'single',
        options: [
          { value: 'low',  label: 'Menos de 1 hora' },
          { value: 'med',  label: '1 a 3 horas' },
          { value: 'high', label: 'Más de 3 horas' },
        ],
      },
    ],
  },
]
