export const AREA_QUESTIONS = [
  {
    areaId: 'transport',
    areaLabel: 'Transporte',
    areaColor: '#4a90d9',
    questions: [
      {
        id: 'carKm',
        text: '¿Cuántos km haces en coche al año?',
        info: 'Cuenta los km que haces al trabajo, escapadas y vacaciones. Si compartes coche habitualmente, cuenta los km totales.',
        type: 'single',
        options: [
          { value: 'km_a', label: 'Poco — menos de 3.000 km/año' },
          { value: 'km_b', label: 'Uso moderado (3.000–10.000 km/año)' },
          { value: 'km_c', label: 'Uso habitual (10.000–20.000 km/año)' },
          { value: 'km_d', label: 'Lo uso mucho — más de 20.000 km/año' },
          { value: 'km_e', label: 'No tengo coche o no lo uso' },
        ],
      },
      {
        id: 'carType',
        text: '¿Es eléctrico o de gasolina/diésel?',
        type: 'single',
        showIf: (answers) => answers.carKm !== 'km_e',
        options: [
          { value: 'gasoline', label: 'Gasolina o diésel' },
          { value: 'electric', label: 'Eléctrico' },
        ],
      },
      {
        id: 'flights',
        text: '¿Cuántos vuelos haces al año?',
        info: 'Cuenta los vuelos de ida y vuelta como uno. Pon 0 si no vuelas.',
        type: 'flights',
        options: [
          { value: 'flightShort',  emoji: '✈️', label: 'Cortos (menos de 3h, ej. Madrid–París)' },
          { value: 'flightMedium', emoji: '🌍', label: 'Medianos (3–6h, ej. Madrid–Estambul)' },
          { value: 'flightLong',   emoji: '🌐', label: 'Transoceánicos (más de 6h, ej. Madrid–Nueva York)' },
        ],
      },
      {
        id: 'train',
        text: '¿Cuánto usas el tren?',
        info: 'Incluye viajes de trabajo, vacaciones y escapadas.',
        type: 'single',
        options: [
          { value: '3a', label: 'Poco (menos de 1.000 km/año)' },
          { value: '3b', label: 'Bastante para vacaciones y viajes (1.000–5.000 km)' },
          { value: '3c', label: 'A diario o muy frecuentemente (más de 10.000 km)' },
          { value: '3d', label: 'No uso el tren' },
        ],
      },
      {
        id: 'moto',
        text: '¿Tienes moto o scooter de gasolina?',
        type: 'single',
        options: [
          { value: '4a', label: 'Casi nada (menos de 150 km/año)' },
          { value: '4b', label: 'La uso a diario (~500 km/año)' },
          { value: '4c', label: 'La uso para todo (más de 1.000 km/año)' },
          { value: '4d', label: 'No tengo moto' },
        ],
      },
      {
        id: 'urbanMobility',
        text: '¿Cómo te mueves habitualmente por la ciudad?',
        info: 'Los trayectos cortos en ciudad son donde hay más margen de mejora.',
        type: 'single',
        options: [
          { value: '5a', label: 'A pie' },
          { value: '5b', label: 'Bicicleta convencional' },
          { value: '5c', label: 'Bicicleta eléctrica' },
          { value: '5d', label: 'Patinete eléctrico' },
          { value: '5e', label: 'Transporte público urbano (bus, metro, tranvía)' },
          { value: '5f', label: 'Taxi / Uber / Cabify' },
        ],
      },
      {
        id: 'telework',
        text: '¿Puedes teletrabajar? ¿Con qué frecuencia lo haces?',
        info: 'Con un desplazamiento medio de 30 km en coche, teletrabajar 5 días/semana puede ahorrar hasta ~800 kgCO₂e/año.',
        type: 'single',
        isSensibilization: true,
        options: [
          { value: 'always',  label: 'Siempre teletrabajo' },
          { value: 'mostly',  label: '3–5 días/semana (principalmente remoto)' },
          { value: 'partial', label: '1–2 días/semana' },
          { value: 'never',   label: 'Nunca, voy a la oficina todos los días' },
        ],
      },
    ],
  },
  {
    areaId: 'energy',
    areaLabel: 'Vivienda',
    areaColor: '#e8a020',
    questions: [
      {
        id: 'householdSize',
        text: '¿Cuántas personas vivís en casa?',
        info: 'El número de personas reparte los gastos energéticos del hogar. Afecta al cálculo per cápita de calefacción y agua caliente.',
        type: 'single',
        options: [
          { value: '1',  label: '1 persona (vivo solo/a)' },
          { value: '2',  label: '2 personas' },
          { value: '3',  label: '3 personas' },
          { value: '4+', label: '4 o más personas' },
        ],
      },
      {
        id: 'homeType',
        text: '¿En qué tipo de vivienda vives?',
        info: 'El tamaño de la vivienda afecta directamente al consumo de calefacción y refrigeración.',
        type: 'single',
        options: [
          { value: '25a', label: 'Piso pequeño / estudio (~45 m²)' },
          { value: '25b', label: 'Piso de 2–3 habitaciones (~80–120 m²)' },
          { value: '25c', label: 'Casa grande o chalet (más de 180 m²)' },
        ],
      },
      {
        id: 'heating',
        text: '¿Qué sistema de calefacción tienes?',
        info: 'Esta pregunta cubre calefacción, agua caliente y cocina. Factor de emisión adaptado a la red española.',
        type: 'single',
        options: [
          { value: '26a', label: 'Sin calefacción' },
          { value: '26b', label: 'Calefacción eléctrica (resistencia)' },
          { value: '26c', label: 'Caldera de gas natural' },
          { value: '26d', label: 'Gasóleo / gasoil' },
          { value: '26e', label: 'Pellets de madera' },
          { value: '26f', label: 'Bomba de calor / aerotermia' },
          { value: '26g', label: 'No sé / combinado' },
        ],
      },
      {
        id: 'renewable',
        text: '¿Tienes paneles solares o has contratado tarifa de energía 100% renovable?',
        info: 'La energía renovable reduce tu huella eléctrica y también tu dependencia de combustibles importados.',
        type: 'single',
        options: [
          { value: 'a', label: 'Sí, tengo paneles solares en casa' },
          { value: 'b', label: 'Tengo tarifa de electricidad 100% renovable certificada' },
          { value: 'c', label: 'No, consumo el mix eléctrico convencional' },
        ],
      },
      {
        id: 'hasAC',
        text: '¿Tienes aire acondicionado?',
        info: 'Si tienes ventiladores pero no aire acondicionado, marca No.',
        type: 'single',
        options: [
          { value: 'yes', label: 'Sí tengo aire acondicionado' },
          { value: 'no',  label: 'No tengo aire acondicionado' },
        ],
      },
      {
        id: 'pool',
        text: '¿Tienes en casa...?',
        type: 'single',
        options: [
          { value: 'privatePool',   label: 'Piscina privada' },
          { value: 'communityPool', label: 'Piscina comunitaria' },
          { value: 'noPool',        label: 'No tengo piscina' },
        ],
      },
      {
        id: 'homeHabits',
        text: '¿Haces alguna de estas cosas en casa? (selecciona todas las que apliquen)',
        info: 'Pequeñas acciones que reducen el consumo energético del hogar.',
        type: 'multi',
        noneValue: 'none',
        options: [
          { value: 'closeWindows', label: 'Cierro ventanas cuando tengo calefacción encendida' },
          { value: 'thermostat19', label: 'Pongo la calefacción a 19–20°C (no más)' },
          { value: 'ledBulbs',     label: 'Tengo todas las bombillas LED' },
          { value: 'ecoPrograms',  label: 'Uso los programas eco de la lavadora y lavavajillas' },
          { value: 'none',         label: 'No hago nada de esto' },
        ],
      },
      {
        id: 'vacationNights',
        text: 'Cuando te vas de vacaciones, ¿dónde te quedas?',
        info: 'Piensa en un año típico. Puedes dejar en 0 los que no uses.',
        type: 'nights',
        options: [
          { value: 'hotelNights',   label: 'Hotel',                          emoji: '🏨' },
          { value: 'hostelNights',  label: 'Albergue / hostel',              emoji: '🛏️' },
          { value: 'campingNights', label: 'Camping',                        emoji: '⛺' },
          { value: 'airbnbNights',  label: 'Apartamento turístico (Airbnb)', emoji: '🏠' },
          { value: 'secondHome',    label: 'Segunda residencia propia',      emoji: '🏡' },
          { value: 'friendsNights', label: 'Casa de amigos o familiares',    emoji: '👨‍👩‍👧' },
        ],
      },
    ],
  },
  {
    areaId: 'food',
    areaLabel: 'Alimentación',
    areaColor: '#5aab5a',
    questions: [
      {
        id: 'breakfastDays',
        text: '¿Qué sueles desayunar durante la semana?',
        info: 'Distribuye tus 7 días entre los tipos de desayuno. Si también almuerzas, activa la opción × 2.',
        type: 'weekDistribution',
        maxDays: 7,
        allowDouble: true,
        options: [
          { value: '6a', label: 'Bollería o tostadas con mermelada' },
          { value: '6b', label: 'Leche o yogur con cereales/granola' },
          { value: '6c', label: 'Tostadas, jamón y tomate' },
          { value: '6d', label: 'Solo fruta' },
          { value: '6e', label: 'Mix variado (huevo + fruta + tostadas)' },
          { value: '6f', label: 'No desayuno', isNone: true },
        ],
      },
      {
        id: 'hotDrinksCount',
        text: '¿Cuántas bebidas calientes tomas al día?',
        info: 'Indica cuántas unidades de cada tipo tomas de media al día.',
        type: 'dailyCount',
        options: [
          { value: '7a', label: 'No tomo bebidas calientes', isNone: true },
          { value: '7b', label: 'Leche con cacao' },
          { value: '7c', label: 'Té' },
          { value: '7d_cow', label: 'Café con leche de vaca' },
          { value: '7d_veg', label: 'Café con leche vegetal (avena)' },
          { value: '7d_chai', label: 'Chai latte' },
          { value: '7e', label: 'Café solo' },
        ],
      },
      {
        id: 'alcohol',
        text: '¿Cuánto bebes durante una semana normal (incluyendo fin de semana)?',
        info: 'Sin juicios — todo suma a tu huella. Piensa en una semana típica incluyendo el finde. Deja en 0 lo que no tomes.',
        type: 'drinks',
        options: [
          { value: 'soda',    label: 'Refrescos',  sublabel: 'Coca-Cola, Fanta, energéticas...', emoji: '🥤' },
          { value: 'wine',    label: 'Vino',       sublabel: 'Copa de 150 ml',                   emoji: '🍷' },
          { value: 'beer',    label: 'Cerveza',    sublabel: 'Caña o botellín (330 ml)',          emoji: '🍺' },
          { value: 'spirits', label: 'Destilados', sublabel: 'Gin, whisky, vodka... (50 ml)',     emoji: '🥃' },
        ],
      },
      {
        id: 'lunchDays',
        text: '¿Qué sueles comer al mediodía en una semana típica?',
        info: 'Distribuye tus 7 comidas de la semana entre los tipos. Tanto en casa como en restaurante.',
        type: 'weekDistribution',
        maxDays: 7,
        allowDouble: false,
        options: [
          { value: '9a', label: 'Vegana' },
          { value: '9b', label: 'Vegetariana' },
          { value: '9c', label: 'Carne blanca (pollo, pavo...)' },
          { value: '9d', label: 'Pescado' },
          { value: '9e', label: 'Carne roja (ternera, cerdo...)' },
          { value: 'none', label: 'No como', isNone: true },
        ],
      },
      {
        id: 'dinnerDays',
        text: '¿Qué sueles cenar en una semana típica?',
        info: 'Distribuye tus 7 cenas de la semana entre los tipos.',
        type: 'weekDistribution',
        maxDays: 7,
        allowDouble: false,
        options: [
          { value: '10a', label: 'Vegana' },
          { value: '10b', label: 'Vegetariana' },
          { value: '10c', label: 'Carne blanca (pollo, pavo...)' },
          { value: '10d', label: 'Pescado' },
          { value: '10e', label: 'Carne roja (ternera, cerdo...)' },
          { value: 'none', label: 'No ceno', isNone: true },
        ],
      },
      {
        id: 'bottledWater',
        text: '¿Bebes agua embotellada?',
        info: 'Si bebes principalmente del grifo, marca que no. El agua del grifo española es segura en la mayoría de ciudades.',
        type: 'single',
        options: [
          { value: '13a', label: 'Sí, compramos agua embotellada en casa' },
          { value: '13b', label: 'A veces compro alguna botella' },
          { value: '13c', label: 'Nunca, bebo del grifo' },
        ],
      },
      {
        id: 'foodHabits',
        text: '¿Sueles hacer algo de esto? (selecciona todas las que apliquen)',
        info: 'Pequeñas acciones que reducen tu huella alimentaria.',
        type: 'multi',
        noneValue: 'none',
        options: [
          { value: 'localFood',   label: 'Compro productos locales y de temporada' },
          { value: 'composting',  label: 'Composting en casa' },
          { value: 'noFoodWaste', label: 'Evito el desperdicio alimentario' },
          { value: 'none',        label: 'No hago nada de esto' },
        ],
      },
      {
        id: 'deliveryPerWeek',
        text: '¿Cuántos pedidos a domicilio haces a la semana?',
        info: 'Cada pedido suma aproximadamente 3 kgCO₂e (transporte última milla + packaging).',
        type: 'stepper',
        min: 0,
        max: 20,
      },
    ],
  },
  {
    areaId: 'consumption',
    areaLabel: 'Compras y hábitos',
    areaColor: '#b07a30',
    questions: [
      {
        id: 'clothes',
        text: '¿Cuánta ropa nueva compras al año? (prendas y zapatos incluidos)',
        info: 'Jerseys, pantalones, abrigos, zapatos... Cuenta todo lo que sea nuevo. La ropa de segunda mano tiene una huella casi nula.',
        type: 'single',
        options: [
          { value: '15a', label: '2 o menos prendas' },
          { value: '15b', label: '3–5 prendas' },
          { value: '15c', label: '6–10 prendas' },
          { value: '15d', label: '11–20 prendas' },
          { value: '15e', label: '21–30 prendas' },
          { value: '15f', label: 'Más de 30 prendas' },
          { value: '15g', label: 'Compro principalmente de segunda mano' },
        ],
      },
      {
        id: 'electronics',
        text: '¿Qué aparatos nuevos has comprado en el último año? (selecciona todos)',
        info: 'Si lo compraste hace 1-2 años puedes contarlo. Si fue hace más de 3 años, no lo cuentes.',
        type: 'multi',
        noneValue: '16i',
        options: [
          { value: '16a', label: 'Smartphone' },
          { value: '16b', label: 'Tablet' },
          { value: '16c', label: 'Ordenador portátil' },
          { value: '16d', label: 'Ordenador de sobremesa' },
          { value: '16e', label: 'Televisor' },
          { value: '16f', label: 'Consola tipo PS / Xbox' },
          { value: '16g', label: 'Cámara de fotos' },
          { value: '16h', label: 'Reloj inteligente / smartwatch' },
          { value: '16i', label: 'Ninguno' },
        ],
      },
      {
        id: 'appliances',
        text: '¿Qué electrodomésticos de menos de 5 años tienes en casa? (selecciona todos)',
        info: 'La fabricación de electrodomésticos tiene una huella importante. Si son de hace más de 5 años, no los cuentes.',
        type: 'multi',
        noneValue: '19i',
        options: [
          { value: '19a', label: 'Lavadora' },
          { value: '19b', label: 'Secadora' },
          { value: '19c', label: 'Lavavajillas' },
          { value: '19d', label: 'Frigorífico' },
          { value: '19e', label: 'Horno' },
          { value: '19f', label: 'Congelador' },
          { value: '19g', label: 'Microondas' },
          { value: '19h', label: 'Televisor' },
          { value: '19i', label: 'Ninguno reciente' },
        ],
      },
      {
        id: 'pets',
        text: '¿Tienes mascotas? (selecciona todas)',
        info: 'La alimentación de las mascotas (sobre todo perros y gatos) tiene una huella de carbono real — principalmente por la carne que contiene su comida.',
        type: 'multi',
        noneValue: 'none',
        options: [
          { value: 'bigDog',   label: 'Perro grande (más de 20 kg)' },
          { value: 'medDog',   label: 'Perro mediano (10–20 kg)' },
          { value: 'smallDog', label: 'Perro pequeño (menos de 10 kg)' },
          { value: 'cat',      label: 'Gato' },
          { value: 'none',     label: 'No tengo mascotas' },
        ],
      },
      {
        id: 'hygiene',
        text: '¿Cuántos productos de higiene y limpieza compras al mes?',
        info: 'Champú, gel, maquillaje, cremas, detergentes, productos de limpieza del hogar...',
        type: 'single',
        options: [
          { value: '22a', label: 'Pocos (1–2 al mes)' },
          { value: '22b', label: 'Normal (4–5 al mes)' },
          { value: '22c', label: 'Muchos (alrededor de 10)' },
        ],
      },
      {
        id: 'smoking',
        text: '¿Fumas o vapeas?',
        type: 'single',
        options: [
          { value: '23a', label: 'No fumo' },
          { value: '23b', label: 'Vapeo' },
          { value: '23c', label: 'Poco (1 paquete al mes)' },
          { value: '23d', label: 'Normal (1 paquete a la semana)' },
          { value: '23e', label: 'Mucho (1 paquete al día)' },
        ],
      },
      {
        id: 'sports',
        text: '¿Qué deportes practicas habitualmente?',
        info: 'Selecciona todos los que practiques. La huella incluye instalaciones, desplazamientos y equipamiento.',
        type: 'multi',
        noneValue: 'none',
        options: [
          { value: 'outdoor',    label: 'Deportes individuales al aire libre (running, senderismo...)' },
          { value: 'cycling',    label: 'Ciclismo' },
          { value: 'racket',     label: 'Deportes de raqueta o balón (tenis, fútbol, pádel...)' },
          { value: 'pool',       label: 'Deportes de piscina (natación, water polo...)' },
          { value: 'gym',        label: 'Gimnasio o sala de musculación' },
          { value: 'fitness',    label: 'Fitness, yoga o pilates' },
          { value: 'martial',    label: 'Artes marciales y deportes de combate' },
          { value: 'athletics',  label: 'Atletismo' },
          { value: 'equestrian', label: 'Hípica' },
          { value: 'golf',       label: 'Golf' },
          { value: 'nautical',   label: 'Deportes acuáticos (kayak, surf, vela...)' },
          { value: 'ski',        label: 'Deportes de invierno (esquí, snowboard...)' },
          { value: 'motor',      label: 'Deportes de motor (karting, motocross...)' },
          { value: 'climbing',   label: 'Escalada' },
          { value: 'none',       label: 'No practico deporte' },
        ],
      },
    ],
  },
  {
    areaId: 'waste',
    areaLabel: 'Vida digital',
    areaColor: '#7a7aaa',
    questions: [
      {
        id: 'videoCalls',
        text: '¿Cuántas horas a la semana haces videollamadas? (Zoom, Teams, Meet...)',
        type: 'single',
        options: [
          { value: 'vc_none',      label: 'Nunca o casi nunca (0–0,5 h/semana)' },
          { value: 'vc_sometimes', label: 'A veces (1–2 h/semana)' },
          { value: 'vc_often',     label: 'Bastante (3–5 h/semana)' },
          { value: 'vc_lots',      label: 'Mucho, me encanta videollamar (más de 5 h/semana)' },
        ],
      },
      {
        id: 'streaming',
        text: '¿Cuántas horas a la semana ves streaming? (Netflix, YouTube, HBO...)',
        type: 'single',
        options: [
          { value: 'st_none',   label: 'No veo nada' },
          { value: 'st_little', label: 'Poco (1–3 h/semana)' },
          { value: 'st_often',  label: 'Bastante (1–2 h/día)' },
          { value: 'st_lots',   label: 'Mucho (más de 3 h/día)' },
        ],
      },
      {
        id: 'socialMedia',
        text: '¿Cuántas horas a la semana usas redes sociales? (Instagram, TikTok, X...)',
        type: 'single',
        options: [
          { value: 'sm_none',   label: 'No tengo redes sociales' },
          { value: 'sm_little', label: 'Poco (1–3 h/semana)' },
          { value: 'sm_often',  label: 'Bastante (1–2 h/día)' },
          { value: 'sm_lots',   label: 'Mucho (más de 3 h/día)' },
        ],
      },
      {
        id: 'aiUsage',
        text: '¿Cuánto usas herramientas de IA al día? (ChatGPT, Claude, Copilot...)',
        info: 'Una consulta a un modelo de IA grande consume ~10× más energía que una búsqueda en Google.',
        type: 'single',
        options: [
          { value: 'none',   label: 'No uso IA' },
          { value: 'low',    label: 'Poco (menos de 30 min/día)' },
          { value: 'medium', label: 'Bastante (30 min – 2h/día)' },
          { value: 'high',   label: 'Mucho (más de 2h/día)' },
        ],
      },
    ],
  },
]
