export const AREA_QUESTIONS = [
  {
    areaId: 'transport',
    areaLabel: 'Transporte',
    areaEmoji: '🚗',
    areaColor: '#4a90d9',
    questions: [
      {
        id: 'car',
        text: '¿Cuántos kilómetros recorres en coche al año?',
        type: 'single',
        options: [
          { value: '1a', label: 'Menos de 5.000 km' },
          { value: '1b', label: '5.000 – 15.000 km' },
          { value: '1c', label: '15.000 – 25.000 km' },
          { value: '1d', label: 'Más de 25.000 km' },
          { value: '1e', label: 'No tengo coche' },
        ],
      },
      {
        id: 'electricCar',
        text: '¿Con qué tipo de combustible funciona tu coche?',
        info: 'Si no tienes coche, puedes omitir esta pregunta.',
        type: 'single',
        options: [
          { value: 'a', label: 'Eléctrico' },
          { value: 'b', label: 'Híbrido enchufable (PHEV)' },
          { value: 'c', label: 'Diésel' },
          { value: 'd', label: 'GLP o gas natural' },
          { value: 'e', label: 'Gasolina' },
        ],
      },
      {
        id: 'flights',
        text: '¿Qué tipos de vuelo has realizado este año?',
        info: 'Selecciona todos los que apliquen.',
        type: 'multi',
        noneValue: 'noFlights',
        options: [
          { value: 'flightShort',  label: 'Vuelo corta distancia (nacional, ≤2 h)' },
          { value: 'flightMedium', label: 'Vuelo media distancia (europeo, 2–5 h)' },
          { value: 'flightLong',   label: 'Vuelo larga distancia (intercontinental, >5 h)' },
          { value: 'noFlights',    label: 'No he volado este año' },
        ],
      },
      {
        id: 'train',
        text: '¿Con qué frecuencia viajas en tren de larga distancia (AVE, Intercity)?',
        type: 'single',
        options: [
          { value: '3a', label: 'Con frecuencia (varios viajes al mes)' },
          { value: '3b', label: 'Ocasionalmente (algunos viajes al año)' },
          { value: '3c', label: 'Raramente (uno o dos al año)' },
          { value: '3d', label: 'Nunca' },
        ],
      },
      {
        id: 'moto',
        text: '¿Utilizas moto o ciclomotor habitualmente?',
        type: 'single',
        options: [
          { value: '4a', label: 'Ocasionalmente' },
          { value: '4b', label: 'Varios días a la semana' },
          { value: '4c', label: 'A diario o casi a diario' },
          { value: '4d', label: 'No tengo moto' },
        ],
      },
      {
        id: 'urbanMobility',
        text: '¿Cómo te desplazas habitualmente por la ciudad?',
        type: 'single',
        options: [
          { value: '5a', label: 'A pie o en bicicleta' },
          { value: '5b', label: 'Transporte público (metro, bus, cercanías)' },
          { value: '5c', label: 'Combinado (público + coche o moto)' },
          { value: '5d', label: 'Principalmente en coche' },
          { value: '5e', label: 'Siempre en coche' },
        ],
      },
    ],
  },
  {
    areaId: 'energy',
    areaLabel: 'Hogar',
    areaEmoji: '🏠',
    areaColor: '#e8a020',
    questions: [
      {
        id: 'householdSize',
        text: '¿Cuántas personas vivís en tu hogar?',
        type: 'single',
        options: [
          { value: '1',  label: '1 persona (vivo solo/a)' },
          { value: '2',  label: '2 personas' },
          { value: '3',  label: '3 personas' },
          { value: '4+', label: '4 o más personas' },
        ],
      },
      {
        id: 'homeType',
        text: '¿En qué tipo de vivienda vives?',
        type: 'single',
        options: [
          { value: '25a', label: 'Piso o apartamento pequeño (<70 m²)' },
          { value: '25b', label: 'Piso o apartamento grande (≥70 m²)' },
          { value: '25c', label: 'Casa unifamiliar o adosado' },
        ],
      },
      {
        id: 'heating',
        text: '¿Con qué sistema calientas tu hogar en invierno?',
        type: 'single',
        options: [
          { value: '26a', label: 'Sin calefacción' },
          { value: '26b', label: 'Gas natural' },
          { value: '26c', label: 'Gasoil o gasóleo' },
          { value: '26d', label: 'Eléctrica (radiadores o suelo radiante)' },
          { value: '26e', label: 'Biomasa o pellets' },
          { value: '26f', label: 'Bomba de calor o aerotermia' },
        ],
      },
      {
        id: 'renewable',
        text: '¿Tu hogar usa energía renovable?',
        type: 'single',
        options: [
          { value: 'a', label: 'Sí, placas solares o tarifa 100% verde' },
          { value: 'b', label: 'Parcialmente (tarifa verde o comunidad solar)' },
          { value: 'c', label: 'No, red eléctrica convencional' },
        ],
      },
      {
        id: 'hasAC',
        text: '¿Usas aire acondicionado en verano?',
        type: 'single',
        options: [
          { value: 'no',  label: 'No' },
          { value: 'yes', label: 'Sí' },
        ],
      },
      {
        id: 'homeHabits',
        text: '¿Cuáles de estos hábitos practicas en casa?',
        info: 'Selecciona todos los que apliquen.',
        type: 'multi',
        noneValue: 'none',
        options: [
          { value: 'closeWindows', label: 'Cierro ventanas cuando la calefacción o el aire está encendido' },
          { value: 'thermostat19', label: 'Mantengo el termostato a 19–20 °C en invierno' },
          { value: 'ledBulbs',     label: 'Tengo iluminación LED en toda la casa' },
          { value: 'ecoPrograms',  label: 'Uso programas ecológicos en lavadora y lavavajillas' },
          { value: 'none',         label: 'Ninguno de estos hábitos' },
        ],
      },
    ],
  },
  {
    areaId: 'food',
    areaLabel: 'Alimentación',
    areaEmoji: '🥗',
    areaColor: '#5aab5a',
    questions: [
      {
        id: 'milkType',
        text: '¿Qué tipo de leche consumes habitualmente?',
        type: 'single',
        options: [
          { value: 'a', label: 'Leche de vaca' },
          { value: 'b', label: 'Bebida vegetal (avena, soja, almendra...)' },
          { value: 'c', label: 'No tomo leche ni bebidas vegetales' },
        ],
      },
      {
        id: 'hotDrinks',
        text: '¿Qué bebidas calientes consumes habitualmente?',
        type: 'single',
        options: [
          { value: '7a', label: 'Café con leche de vaca' },
          { value: '7b', label: 'Café solo o con leche vegetal' },
          { value: '7c', label: 'Té o infusiones' },
          { value: '7d', label: 'No tomo bebidas calientes' },
        ],
      },
      {
        id: 'lunch',
        text: '¿Cómo describirías tu almuerzo habitual?',
        type: 'single',
        options: [
          { value: '9a', label: 'Vegano (sin productos animales)' },
          { value: '9b', label: 'Vegetariano (huevos y lácteos sí)' },
          { value: '9c', label: 'Pescado o marisco, sin carne' },
          { value: '9d', label: 'Poca carne (principalmente aves)' },
          { value: '9e', label: 'Carne moderada (varios días a la semana)' },
          { value: '9f', label: 'Mucha carne roja (vacuno, cerdo, cordero)' },
        ],
      },
      {
        id: 'dinner',
        text: '¿Cómo describirías tu cena habitual?',
        type: 'single',
        options: [
          { value: '10a', label: 'Vegana (sin productos animales)' },
          { value: '10b', label: 'Vegetariana (huevos y lácteos sí)' },
          { value: '10c', label: 'Pescado o marisco, sin carne' },
          { value: '10d', label: 'Poca carne (principalmente aves)' },
          { value: '10e', label: 'Carne moderada (varios días a la semana)' },
          { value: '10f', label: 'Mucha carne roja (vacuno, cerdo, cordero)' },
        ],
      },
      {
        id: 'bottledWater',
        text: '¿Qué agua bebes habitualmente?',
        type: 'single',
        options: [
          { value: '13a', label: 'Principalmente agua embotellada' },
          { value: '13b', label: 'Mitad grifo, mitad embotellada' },
          { value: '13c', label: 'Solo agua del grifo o filtrada' },
        ],
      },
      {
        id: 'foodHabits',
        text: '¿Cuáles de estos hábitos tienes con la alimentación?',
        info: 'Selecciona todos los que apliquen.',
        type: 'multi',
        noneValue: 'none',
        options: [
          { value: 'localFood',   label: 'Compro productos locales y de temporada' },
          { value: 'composting',  label: 'Hago compost o uso cubo de orgánico' },
          { value: 'noFoodWaste', label: 'Planifico mis menús para no desperdiciar comida' },
          { value: 'organic',     label: 'Compro productos ecológicos habitualmente' },
          { value: 'noPlastic',   label: 'Evito envases de plástico o compro a granel' },
          { value: 'none',        label: 'Ninguno de estos hábitos' },
        ],
      },
    ],
  },
  {
    areaId: 'consumption',
    areaLabel: 'Consumo',
    areaEmoji: '🛍️',
    areaColor: '#b07a30',
    questions: [
      {
        id: 'clothes',
        text: '¿Cuánta ropa nueva compras al año?',
        type: 'single',
        options: [
          { value: '15a', label: '1 – 5 prendas nuevas' },
          { value: '15b', label: '5 – 10 prendas nuevas' },
          { value: '15c', label: '10 – 15 prendas nuevas' },
          { value: '15d', label: '15 – 20 prendas nuevas' },
          { value: '15e', label: '20 – 30 prendas nuevas' },
          { value: '15f', label: 'Más de 30 prendas nuevas' },
          { value: '15g', label: 'Casi todo de segunda mano o no compro' },
        ],
      },
      {
        id: 'electronics',
        text: '¿Qué dispositivos electrónicos has comprado nuevos este año?',
        info: 'Selecciona todos los que hayas comprado.',
        type: 'multi',
        noneValue: '16i',
        options: [
          { value: '16a', label: 'Smartphone' },
          { value: '16b', label: 'Tablet' },
          { value: '16c', label: 'Portátil o PC de sobremesa' },
          { value: '16d', label: 'Consola de videojuegos' },
          { value: '16e', label: 'Televisor' },
          { value: '16f', label: 'Smartwatch o pulsera de actividad' },
          { value: '16g', label: 'Auriculares o altavoces inteligentes' },
          { value: '16h', label: 'Otros dispositivos pequeños' },
          { value: '16i', label: 'Ninguno' },
        ],
      },
      {
        id: 'appliances',
        text: '¿Qué electrodomésticos has comprado nuevos este año?',
        info: 'Selecciona todos los que hayas comprado.',
        type: 'multi',
        noneValue: '19i',
        options: [
          { value: '19a', label: 'Nevera, congelador o combi' },
          { value: '19b', label: 'Lavadora' },
          { value: '19c', label: 'Lavavajillas' },
          { value: '19d', label: 'Horno o cocina' },
          { value: '19e', label: 'Microondas' },
          { value: '19f', label: 'Aspiradora o robot de limpieza' },
          { value: '19g', label: 'Pequeños electrodomésticos (freidora, batidora...)' },
          { value: '19h', label: 'Purificador de aire o climatizador' },
          { value: '19i', label: 'Ninguno' },
        ],
      },
      {
        id: 'pets',
        text: '¿Qué mascotas tienes?',
        info: 'Selecciona todas las que tengas.',
        type: 'multi',
        noneValue: 'none',
        options: [
          { value: 'bigDog',   label: 'Perro grande (>15 kg)' },
          { value: 'smallDog', label: 'Perro pequeño (<15 kg)' },
          { value: 'cat',      label: 'Gato' },
          { value: 'rabbit',   label: 'Conejo' },
          { value: 'bird',     label: 'Ave (loro, canario...)' },
          { value: 'none',     label: 'No tengo mascotas' },
        ],
      },
      {
        id: 'hygiene',
        text: '¿Cómo calificarías tu consumo de productos de higiene y limpieza?',
        type: 'single',
        options: [
          { value: '22a', label: 'Bajo: productos concentrados, a granel o ecológicos' },
          { value: '22b', label: 'Medio: consumo convencional habitual' },
          { value: '22c', label: 'Alto: muchos productos y envases frecuentes' },
        ],
      },
      {
        id: 'smoking',
        text: '¿Fumas?',
        type: 'single',
        options: [
          { value: '23a', label: 'No fumo' },
          { value: '23b', label: 'Ocasionalmente (algún cigarrillo a la semana)' },
          { value: '23c', label: 'Moderado (menos de 10 al día)' },
          { value: '23d', label: 'Un paquete al día (10–20 cigarrillos)' },
          { value: '23e', label: 'Más de un paquete al día' },
        ],
      },
    ],
  },
  {
    areaId: 'waste',
    areaLabel: 'Huella Digital',
    areaEmoji: '📱',
    areaColor: '#7a7aaa',
    questions: [
      {
        id: 'videoCalls',
        text: '¿Cuántas horas al día dedicas a videollamadas (Zoom, Teams, Meet...)?',
        type: 'single',
        options: [
          { value: 'none',   label: 'Ninguna o casi ninguna' },
          { value: 'less1h', label: 'Menos de 1 hora' },
          { value: '1to2h',  label: '1 a 2 horas' },
          { value: 'more2h', label: 'Más de 2 horas' },
        ],
      },
      {
        id: 'streaming',
        text: '¿Cuántas horas al día consumes contenido en streaming (Netflix, YouTube, Spotify...)?',
        type: 'single',
        options: [
          { value: 'none',   label: 'Ninguna o casi ninguna' },
          { value: 'less1h', label: 'Menos de 1 hora' },
          { value: '1to4h',  label: '1 a 4 horas' },
          { value: 'more4h', label: 'Más de 4 horas' },
        ],
      },
      {
        id: 'socialMedia',
        text: '¿Cuántas horas al día pasas en redes sociales?',
        type: 'single',
        options: [
          { value: 'less1h', label: 'Menos de 1 hora' },
          { value: '1to2h',  label: '1 a 2 horas' },
          { value: 'more2h', label: 'Más de 2 horas' },
        ],
      },
    ],
  },
]
